language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "iojs"
  - "4"
  - "5.1"
script: echo "code tests" ; npm run test; echo "readme tests" ; npm run test-readme ; echo "documentation example tests" ; npm run test-docs
